version: '3.8'

services:
  host:
    image: inadvertance/baby-foot-host
    build: ./host
    command: dev
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      NODE_ENV: production
      NUXT_ENV_FEATURES_MATCH: "false"
      NUXT_ENV_FEATURES_RANKED: "false"
      NUXT_ENV_FEATURES_STREAM: "false"

  server:
    image: inadvertance/baby-foot-server
    build: ./server
    command: serve
    ports:
      - "4000:4000"
    environment:
      PORT: 4000

  api:
    image: inadvertance/baby-foot-api
    build: ./api
    entrypoint: bash -c "yarn db:migrate && yarn serve"
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    environment:
      PORT: 9000
      ARANGODB_URL: http://db:8529
      LOG_LEVEL: info
      REDIS_URI: redis://redis:6379

  ranking:
    build: ./api
    image: inadvertance/baby-foot-api-ranking-job
    command: jobs:ranking
    depends_on:
      - db
      - redis
    environment:
      ARANGODB_URL: http://db:8529
      LOG_LEVEL: info
      REDIS_URI: redis://redis:6379

  db:
    image: arangodb/arangodb:3.7.2
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - "8529:8529"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
