version: '3.8'

services:
  client:
    image: inadvertance/baby-foot-client
    build: ./client
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

  host:
    image: inadvertance/baby-foot-host
    build: ./host
    ports:
      - "4000:4000"
    environment:
      PORT: 4000

  server:
    image: inadvertance/baby-foot-server
    build: ./server
    ports:
      - "5000:5000"
    environment:
      PORT: 5000

  api:
    image: inadvertance/baby-foot-api
    build: ./api
    ports:
      - "6000:6000"
    environment:
      PORT: 6000
